GET http://localhost:8080/books

###

DELETE http://localhost:8080/books/3

###

DELETE http://localhost:8080/books/999


###
POST http://localhost:8080/books
Content-Type: application/json
Accept: application/json

{
  "title": "Title2",
  "author": "Author2",
  "isbn": "ISBN2",
  "publicationDate": "2023-01-01"
}
